server:
  port: 8082

# config h2
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: passer123
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
